### PR TITLE
SCRUM-957 Added max-width and padding to an extra container property …

### PR DESCRIPTION
**Pull request by azurebrd**
…in css, section colors matching mod colors per mod to css for a section border, solid color border with radius and padding to section.

Not sure yet how to move resources to be a vertical section on the right spanning about + news on an x-large screen.

### CODE REVIEW

**Comment by azurebrd** [comment]
New code should take care of SCRUM-957

**Review by nuin — APPROVED** [review]

**Comment by nuin** [comment]
From a code perspective, it looks good. And from a design perspective I think that's what they want, so all in all a perfect PR.

**Comment by azurebrd** [comment]
Thanks @nuin !

**Comment by azurebrd** [comment]
live now

**Comment by azurebrd** [comment]
@valearna fyi: removed `<div className='col-md-8'>` so the news text would line up with the about text in wordpressNews.js  if you really think it should go back to that we can discuss

**Comment by nuin** [comment]
This is the main reason I don't like borders

image

The pages gets unbalanced, "boxes" have different sizes, and will have for all MODs, and you lose standardization, allowing for unbalance on what is presented for each mode. But management loves it, so we are happy.

thanks for working on this @azurebrd

**Comment by nuin** [comment]
Another example is the `privacy-warranty-licensing` page

**Pull request merged**
