### PR TITLE
fixing Jbrowse link to point at "assembly picker"

### PR DESCRIPTION
**Pull request by scottcain**

### CODE REVIEW

**Comment by christabone** [comment]
@scottcain We used to have a "hot fix" protocol somewhere because this image is already deployed to production. I'd wait to hear from @oblodgett first just to see the best course of action.

**Comment by oblodgett** [comment]
In this PR also needs the 6 -> 7 on the AboutSection

**Comment by scottcain** [comment]
@oblodgett err, what?

**Comment by oblodgett** [comment]
Hot fix I did this morning:
https://github.com/alliance-genome/agr_ui/blob/master/apps/main-app/src/containers/homepage/AboutSection.js
6 -> 7

**Comment by scottcain** [comment]
Added the 6->7 change on the about

**Comment by oblodgett** [comment]
@scottcain is this ready to go at this point?

**Review by oblodgett — APPROVED** [review]

**Comment by oblodgett** [comment]
Probably going to have to deal with this on Monday.

**Pull request merged**
