### PR TITLE
Fix AGR-2091

### PR DESCRIPTION
**Pull request by nathandunn**
Fixes: 

https://agr-jira.atlassian.net/browse/AGR-2091

### CODE REVIEW

**Comment by nathandunn** [comment]
Shoot . . I wasn't ready . . . you didn't wait for my slack :(

**Comment by nathandunn** [comment]
no worries, what's in there is fine

**Comment by paaatrick** [comment]
If you open a pull request I assume it's, uhh, ready to be pulled in 🤷‍♂

**Comment by nathandunn** [comment]
yeah, I know

**Pull request merged**
