### PR TITLE
uses component which automatically fixes the height - AGR-1146

### PR DESCRIPTION
**Pull request by nathandunn**
Last piece to fix this: 

https://agr-jira.atlassian.net/browse/AGR-1146

ATTN @sibyl229

### CODE REVIEW

**Comment by nathandunn** [comment]
@sibyl229  I leave it up to you, so long as we don't forget. 

My 2 cents is that its problem not introduced in the build.   If I run `npm test` it (continues) to work.    However, previously working builds seem to now fail.  

I'm going to re-run this: https://travis-ci.org/alliance-genome/agr_ui/builds/456076434 (which was previously working) and it now fails. 

Possibly we can go back further, but I think its a problem with a change in travis.

**Comment by nathandunn** [comment]
But we can wait until after Patrick has taken a look as well.

**Comment by sibyl229** [comment]
@nathandunn I don't think we will forget this, because I regularly visit the list of PRs. And I'm sure Patrick will see if before making a major release.

I will take a look at your previous PR and see if I can figure out what broke the build

**Comment by nathandunn** [comment]
@sibyl229  Sounds good. 

If you go back and rebuild that was working in the develop branch:

https://travis-ci.org/alliance-genome/agr_ui/builds

You'll see that you'll be able to break any prior working build on the "develop" branch.   Why largely I think its a travis (or other) dependency issue.

**Pull request merged**
