### PR TITLE
fixes 2241, 2243, and 2239

### PR DESCRIPTION
**Pull request by nathandunn**
please review, just bumps the version of the GFC

### CODE REVIEW

**Comment by nathandunn** [comment]
feel free to merge if approved (whoever gets it first)

**Comment by nathandunn** [comment]
Not sure why pseudogenic transcript is in there, but it is okay

**Comment by paaatrick** [comment]
Did you create this branch from `release-3.1.0` or from `master`? If you created it from `master` that would explain why those extraneous commits are in there.

**Comment by nathandunn** [comment]
@paaatrick  I created those off of master (as I always forget), so that makes esnse.

**Pull request merged**
