### PR TITLE
Use "WB" as the modShortName for "WormBase" (currently short name is same as fullname)

### PR DESCRIPTION
**Pull request by gildossantos**
DO NOT MERGE UNTIL MORE DISCUSSION AT BLUE TEAM DAILY SCRUM

### CODE REVIEW

**Comment by nuin** [comment]
@gildossantos I won't be at the scrum today.

**Comment by azurebrd** [comment]
I think @valearna did that on purpose, but I don't remember why.  It made sense when we were refactoring.  I guess if he's not around, I'd be fine with it if Ranjana's okay with it (as a WB rep and SME for mod landing pages)

**Comment by gildossantos** [comment]
hmm - I guess we use full-length "WormBase" on the Members section of the homepage too. Maybe it was intentional.
But, in that case, "FB" should also be "FlyBase" then.
And I'm sorry if I'm reopening issues that have already been discussed and resolved.

**Comment by azurebrd** [comment]
Not at all :)  I'm good with it ending up either way. (All abbreviations or just some)

**Comment by gildossantos** [comment]
Closing, as I think we need more info on what the MODs want, then we need to take a fresh look across the board at places that we use abbr vs fullname and make sure we implement it according to specs.

**Pull request closed without merging**
