### PR TITLE
SCRUM-1086 Added Search section that only links to Alliance search fo…

### PR DESCRIPTION
**Pull request by azurebrd**
…r specific species.  Cleaned up some commented out stuff

### CODE REVIEW

**Review by ianlongden — APPROVED** [review]
I do not see any tests for this. (you knew it was coming :-) ). If this is because it is experimental and is just while people look at it to see if it is acceptable then it is okay. But I will check later on these added. :-)

**Comment by azurebrd** [comment]
@ianlongden for sure :)  I think they won't quite like how it looks, and we'll have to change the formatting, which might mean having the code diverge from how the resource container handles the content.js data.  Thanks !

**Comment by azurebrd** [comment]
@ianlongden I guess UIPR/BuildAndTest has to pass before it can merge on master, while it didn't on blue_team_code ?

**Comment by azurebrd** [comment]
live.

**Pull request merged**
