### PR TITLE
AGR-960 Show definition links in footnote style

### PR DESCRIPTION
**Pull request by paaatrick**
I also did a little clean up of how we display comma-separated lists. The old method of using `reduce()` was kind of cryptic and not particular declarative.

### CODE REVIEW

**Comment by bryon-czoch** [comment]
Oh nm, I was comparing different viewports

**Comment by paaatrick** [comment]
image

Like so? I guess I don't have strong feelings for either that or the way it's currently implemented.

**Comment by bryon-czoch** [comment]
And comma separated.  https://guides.lib.uw.edu/c.php?g=99161&p=642386

**Comment by paaatrick** [comment]
"How to Format the Paper using AMA Style" 

..... what? Did you paste the wrong link?

**Comment by bryon-czoch** [comment]
yep.

Try "Quick Tips" or "Citing Electronic Sources" in the side nav bar

**Comment by bryon-czoch** [comment]
How about something similar to Wikipedia: 

untitled

**Comment by bryon-czoch** [comment]
Yeah cuz Wikipedia is a paper.

**Pull request merged**
