### PR TITLE
AGR-2271

### PR DESCRIPTION
**Pull request by pjhale**
Fixes AGR 2271 by displaying all variants regardless of pagination.  Uses a separate API call in useAllVariants that ignores the table pagination but uses the filters on the page.  Hopefully this code is consistent with the other react query code... I'm not all that familiar with it yet so this may not be the most concise way to do it.

### CODE REVIEW

**Comment by sibyl229** [comment]
@pjhale you might need to rebase your branch off latest commit on `master`. It's probably what's causing the test to fail.

**Comment by paaatrick** [comment]
I merged `master` into this branch which should clear up the test run failure

**Review by paaatrick — COMMENTED** [review]
I like the overall approach. Two comments/questions:

1. I know there's already enough confusion in the terminology around alleles and variants, but since the API endpoint called by the new hook is `/alleles` I wonder if the hook should be named `useAllAlleles` instead.
2. Did you take a look at the implementation of the `useAlleleVariants` hook? I wonder if the same pattern of calling `useDataTableQuery` (as opposed to calling `useQuery` directly) could be used here as well. In your case you could override properties of the passed-in `tableState` instead of `DEFAULT_TABLE_STATE`. Then you wouldn't have to worry about re-implementing `getFullUrl`.

**Comment by pjhale** [comment]
On the first point I have no issues with renaming the hook to useAllAlleles.  On the second point I did try to use useDataTableQuery first but I was having issues passing the filters through that method without them getting overridden or changing the tableState unintentionally.

**Comment by paaatrick** [comment]
Okay, fine for now then. I might go and take a second look later, time permitting.

**Pull request merged**
