### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by nuin**
removed MOD nname from footer (left space for a possible icon)
some css consolidation
re-added the News section title, keeping the text link

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
@nuin Looks good.  Do you want me to add the icon on the footer ?  Would you be okay with css variables for the colors ?  If you still want to keep making changes, that's good too, no pressure.

**Comment by azurebrd** [comment]
live

**Comment by nuin** [comment]
Let me do some more stuff, I will play with the icon. You can add the variables if you want and we arrange sometime this week to work together on this. I want to change the visit button, I think it needs to be flatter

**Comment by azurebrd** [comment]
@nuin Sounds good.  I'll wait for the css variables until you're not making changes to avoid potential conflicts.  I saw you made the visit button wider and took off the corners.  I was thinking of removing the borders and adding the same box-shadow that the sections use.  I like the general round corners of the sections and in the button, but Shannon would keep telling me to make them less round, so I hear that.  
Did you change something in the resources such that when making the browser narrower, ZFIN's 'Mutants/Transgenics/Phenotypes' split into separate lines ?  Howie pointed out they weren't doing that on Thursday or Friday, but they seem to be good now.

**Comment by nuin** [comment]
I don’t remember touching resources. I will do more tomorrow on the icon.

**Comment by azurebrd** [comment]
*nod*  wondered if it was something about css I missed about changing overflow or something.
No rush, it's looking good, and I don't think there's really much left to do.  Thanks @nuin

**Pull request merged**
