### PR TITLE
Scrum 206

### PR DESCRIPTION
**Pull request by FB-ping**
change the fetchTimeout from 30000 to 60000 to fix the all alleles search error

### CODE REVIEW

**Review by oblodgett — APPROVED** [review]

**Review by gildossantos — CHANGES_REQUESTED** [review]
This PR seems to include a commit from @valearna that removes members section from the homepage and says "!DO NOT MERGE INTO MASTER!".
Maybe @FB-ping needs to create a new branch off master that excludes Valerio's changes before merging into master?

**Comment by valearna** [comment]
It would be better if we can avoid merging 2763275 into master. Is this PR something we need on master or on the 4.2 release branch?

**Comment by FB-ping** [comment]
sorry, it should merge into release-4.2.0, NOT master.

**Comment by gildossantos** [comment]
This PR was closed and replaced by PR #917 (SCRUM-206)

**Pull request closed without merging**
