### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by nuin**
Couple of commits, changes are explained on the commit message

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
That's great @nuin

**Comment by azurebrd** [comment]
@nuin Did you do something to fix the tests ?  I didn't get why they weren't passing before.  Wondering if something needed updating (I didn't see a change to the files for it), or if github was just messing up before, and now it isn't.

**Comment by azurebrd** [comment]
live.

Looks good.

I think the News section when it has just a link, would look better if it kept the "News" heading to look like the ones that an API, but the ticket doesn't say that clearly. https://agr-jira.atlassian.net/browse/SCRUM-626  I'll ask Ceri on the ticket to confirm.

The Footer doesn't say we should use the mod hexagonal icon, but I think that would look more consistent with the Alliance footer.  I don't think it should have the mod name, but I'm less sure about that until trying it / seeing it.  The ticket doesn't explicitly say not to, so I think that'd be good.

Footer could also use icons (like Twitter, YouTube).  

I'll make this comments on the relevant tickets.  @nuin Do you think these are good ideas ?  I don't know if you're planning on making more changes (also, are you still thinking of refactoring the style.scss for the background-color and color ?)  If so, that's great, if not, let me know.

**Comment by nuin** [comment]
I will work on it this evening, we can coordinate to test the display after

**Comment by azurebrd** [comment]
@nuin cool cool.  If at any point you'd like me to take over any part of it, let me know.  No rush.

**Comment by nuin** [comment]
I think the icon looks better on the footer than on the title bar to be honest, so we can get rid of the MOD name from it.

**Comment by azurebrd** [comment]
@nuin Sounds good.

**Pull request merged**
