### PR TITLE
Removed old code and its refernces

### PR DESCRIPTION
**Pull request by ianlongden**

### CODE REVIEW

**Review by azurebrd — COMMENTED** [review]
I thought we wanted to wait to merge blue_team_code into master, to see that that worked, and then try to remove these files and see if things still worked. @ianlongden @nuin

**Comment by ianlongden** [comment]
Ah, yes maybe that would be best. At least we know it can be done fairly easily now.

**Comment by azurebrd** [comment]
Cool, thanks @ianlongden    Hopefully we can get to both today

**Review by nuin — APPROVED** [review]

**Comment by azurebrd** [comment]
Well, this got merged.  It's live now on dev-public-ui

**Pull request merged**
