### PR TITLE
SCRUM-633: Point icons on homepage Members section to MOD landing pages

### PR DESCRIPTION
**Pull request by gildossantos**
It's perhaps too early for this change, but I would please like some feedback on the approach.

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
That looks good to me, although I haven't tried running the code to check it works.

**Comment by gildossantos** [comment]
Thanks Juancarlos! Are you always up this early? :)
It does work when I run it locally, but I'm honestly not sure if that would work in a real situation.

**Comment by azurebrd** [comment]
I see you're importing 
import {Link} from 'react-router-dom';

I'm not sure you need that if you're doing
          <a className={style.member} href='/members/rgd'>

I would think if you're using Link, you might want 
          <Link className={style.member} to='/members/rgd'>

But I'm not sure.  @nuin any thoughts ?

**Comment by azurebrd** [comment]
haha, no, I was so tired I fell asleep around 8 pm and woke up around midnight.  I'm hopefully going back to bed soon to be up for the stand up :)

**Comment by gildossantos** [comment]
ah - I was trying a lot of stuff and the import of Link is a remnant of that. I'll try removing it and the re-test. Thanks for catching that!

**Comment by azurebrd** [comment]
Not at all !  On the Lit curation I'm using Link.  I'm honestly not sure when it should be Link vs regular <a>  It might have to with using history with Router ?  I imagine to keep things consistent <a> is good, unless we have a specific reason to switch.

**Comment by FB-ping** [comment]
only when you render something, you will need to import "Link" from 'react-router-dom'; here this file only serve as "constant", no render, so no need to import, will need in the file which render those links.

**Comment by azurebrd** [comment]
Ah, thanks @FB-ping

**Comment by gildossantos** [comment]
Thanks @FB-ping and @azurebrd! I think I sorta understand that explanation - I'm sure it'll become clearer with more study and practice.
BTW, I removed the Link import and it still works on my local machine (expected I guess).

**Comment by gildossantos** [comment]
Just noticed some small issues (e.g., using MGD not MGI). Will close this draft PR and fix all issues before submitting a new PR that resolves the issues. Again, thanks!

**Comment by nuin** [comment]
@gildossantos Be aware that there was a discussion about MGI/MGD some time ago on the general channel on Slack

**Comment by gildossantos** [comment]
Thanks @nuin - I found that thread. I'll leave it alone :)

**Pull request closed without merging**
