### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by adamgibs**
Update UI to use CRA

### CODE REVIEW

**Comment by oblodgett** [comment]
@adamgibs i doubt these are your errors but i think we should try to clean them up before merging.

**Review by abecerra — COMMENTED** [review]
After deleting node_modules, npm build throws:

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'webpack'

**Comment by adamgibs** [comment]
@oblodgett Yeah, the create react app eslint settings are set up to catch different things so now things in the older code is being caught. I can fix some of the issues now. However, I think the anchor tag errors should be their own ticket since that's more of a refactor.

**Comment by adamgibs** [comment]
@abecerra Try this:

- delete node_modules
- delete package-lock.json
- run npm install --legacy-peer-deps
- run npm run build
- run npm start

**Comment by abecerra** [comment]
> @abecerra Try this:
> 
> * delete node_modules
> * delete package-lock.json
> * run npm install --legacy-peer-deps
> * run npm run build
> * run make uirunstage

I forgot to delete package-lock.json. Gene and allele pages look good!

**Review by abecerra — APPROVED** [review]

**Comment by abecerra** [comment]
Maybe it would be  worth preserving the .editorconfig file?

**Comment by adamgibs** [comment]
@abecerra That's a good point. I don't know if the `.editorconfig` file would work the same in a CRA app. It's worth looking into.

**Review by oblodgett — APPROVED** [review]

**Pull request merged**
