### PR TITLE
fix key warnings

### PR DESCRIPTION
**Pull request by bryon-czoch**

### CODE REVIEW

**Comment by LucyHut** [comment]
@bryon-czoch , the style is messed up on this branch -- I checked the "About US" page and compared it with dev.alliancegenome.org

**Comment by paaatrick** [comment]
@LucyHut dev.alliancegenome.org hasn't been updated in a while. I think I broke those pages with my recent commits. These changes should be fine.

**Comment by LucyHut** [comment]
@paaatrick, thank you for clearing the air .. will you then fix the style or do you want me to include this in one of my wordpress related issues?

**Comment by paaatrick** [comment]
I'm taking care of it. Thanks for finding that for me!

**Pull request merged**
