### PR TITLE
AGR-1851 allele (rebased from master)

### PR DESCRIPTION
**Pull request by sibyl229**

### CODE REVIEW

**Comment by nathandunn** [comment]
this is what it looks like now: 

image

I think that @sabrinatoro wanted it this way, but she'll know what is right / wrong either way.

**Comment by sabrinatoro** [comment]
@nathandunn 
the sequence viewer should be in the variants section, above the variants table. 
please, do NOT have a separate section for this. 
(please refer to the mockups)
Thank you

**Comment by nathandunn** [comment]
@sibyl229  Can you finish this up with putting stuff in the right place?  I haven't been really part of the allele group, I was only trying to get it on the page.   Thanks.

**Comment by sibyl229** [comment]
@sabrinatoro is this document the most up to date allele page mockup? https://docs.google.com/presentation/d/1ozPzIjv9UYqffzFdinMQq0lvo5B438qBOnoOhCdYRvY/edit#slide=id.g7bb47e2341_0_0

**Comment by sabrinatoro** [comment]
Mockup here (slide 14 and 15) 
https://docs.google.com/presentation/d/1Api7KAeg5QPFMVz-jrkIAtlROQiB__hE_Jw5KjF2rlU/edit?usp=sharing
Also: AGR-1878 (https://agr-jira.atlassian.net/browse/AGR-1878)

**Comment by sabrinatoro** [comment]
The mockup that @sibyl229 shared is also correct.

**Comment by sibyl229** [comment]
Thanks @sabrinatoro ! Does this work? Screenshot attached below:
Screen Shot 2020-02-12 at 3 04 24 PM

**Comment by sabrinatoro** [comment]
@sibyl229 
yes, the position of the viewer compare to the table is correct. 
The data is however not showing in the viewer (but I guess this a different type of testing).

**Comment by paaatrick** [comment]
We gotta put this PR to bed. @sabrinatoro if you find the same thing happening when this hits build please open a new ticket for that.

**Comment by sibyl229** [comment]
Thanks @paaatrick !
@sabrinatoro my local development environment wasn't up to date. I should look like:
Screen Shot 2020-02-12 at 3 22 47 PM

**Pull request merged**
