### PR TITLE
Couple of changes

### PR DESCRIPTION
**Pull request by nuin**
merging the new labels for the menu
nginx.conf file without the members redirecte

ignore the test files, just a placeholder and some tests, I will remove them soon

### CODE REVIEW

**Review by valearna — APPROVED** [review]
Thanks @nuin. For the labels, If I'm not wrong we decided to show only the long name, without the abbreviation - e.g., 'Zebrafish Information Network' instead of 'Zebrafish Information Network / ZFIN.

**Comment by gildossantos** [comment]
Tests are stalled, so going to try to close and re-open it.

**Review by gildossantos — DISMISSED** [review]

**Review by azurebrd — DISMISSED** [review]

**Comment by gildossantos** [comment]
Closing this PR as I think the Blue Team agreed we shouldn't merge into master until we have a release ready.

**Comment by azurebrd** [comment]
Thanks @gildossantos :  Paulo, Valerio, and I were talking to Olin and Manuel about this and other open UI PRs, we're all happy you closed it.

**Pull request closed without merging**
