### PR TITLE
Blue team code

### PR DESCRIPTION
**Pull request by nuin**
This is the PR to merge `blue_team_code` into master. Latest PRs were merged, code was merged and testes on a fork and all visual elements seem to be present in the local serve of the website.

I would refrain to push more commits to `blue_team_code` until the end of the sprint just for consistency and remove the necessity of more testing. 

Let me know if you need any more info, and if you are interested you can check. the code on a fork.

### CODE REVIEW

**Comment by nuin** [comment]
What happens upstream of here, I don't know.

**Review by azurebrd — APPROVED** [review]
Looks good.  I'll need to remove some commented out stuff from googleapisMeetings.js later.  We might want to clean up some comments in the content.js later too.
@ianlongden We have a couple of empty files in tests/ jobScript.js and server.js  If that's on purpose, okay, otherwise we should clean that up after this is working on build or stage or wherever it's supposed to.

**Comment by azurebrd** [comment]
Thanks @nuin .  Everyone reviewing this makes sense, so I'm not merging it after approval.  Not committing into blue_team_code until this is merged and worked out also makes sense.  Thanks.

**Comment by azurebrd** [comment]
live (checkout master, pull, npm install, pull again, restarted server)

**Pull request merged**
