### PR TITLE
(WIP) AGR-2535 allele details page and Feature Viewer

### PR DESCRIPTION
**Pull request by sibyl229**
This is still waiting on some API changes. The UI code should be close to its ready state. It would be nice to get reviews from you.

@paaatrick two noteworthy changes, 1) adding the Allele Details page 2) making the table component automatically derive distinct filter values from supplementalData.

@nathandunn @pjhale I moved some logic out of `VariantsSequenceViewer` to its parent components, in order to reuse this component on the new Variant details page. The logic that got moved out involves, 1) calculate fmin, fmax 2) hide viewer while loading 3) display message if no variant is mapped.

If there is anything you are concerned about, please let me know.

### CODE REVIEW

**Review by nathandunn — COMMENTED** [review]
I think moving the logic out makes sense. 

Just need to re-test it when the API changes come through.

**Comment by sibyl229** [comment]
@nathandunn great! Let's do that. The API is mostly functional and the Feature Viewer is being rendered. One case that I haven't been able to check is the when fmax and fmin is outside the range of the gene, because the API is currently missing the variant coordinates for the new page.

**Review by paaatrick — APPROVED** [review]
This looks good to me. I think it definitely makes sense to have the DataTable component know as much about the structure of a "typical" API response as possible. If you have time to go back and look at the other table components that are manually calling `getDistinctFieldValue` just to make everything consistent that would be a nice bonus. Otherwise feel free to merge this whenever you're ready.

**Comment by sibyl229** [comment]
@paaatrick thanks! About the manually invoked `getDistinctFieldValue`, I plan on doing those incrementally, as they require API side change - the filter naming in the URL parameter and the supplementData aren't guaranteed to be the same previously. But I made sure the change is backward compatible, that `filterable` manually set in the column configuration takes precedence over the auto-generated in the DataTable component.

**Comment by sibyl229** [comment]
Since the code is functional, I'm pulling this in, even though the feature isn't complete. I have updated Sabrina on what isn't ready for testing.

**Pull request merged**
