### PR TITLE
Fix AGR-2581 and AGR-2287

### PR DESCRIPTION
**Pull request by lpalbou**
Fix https://agr-jira.atlassian.net/browse/AGR-2581
And https://agr-jira.atlassian.net/browse/AGR-2287

### CODE REVIEW

**Review by sibyl229 — APPROVED** [review]

**Comment by lpalbou** [comment]
Sibyl, I tagged you as reviewer as Patrick is not here anymore. The PR here doesn't say much as the fix was on the GO / ribbon side with our dbxrefs: https://www.npmjs.com/package/@geneontology/dbxrefs and https://github.com/geneontology/wc-ribbon/commit/020f60134eb68d1ea515892c5e0d64e5fd428aff

**Comment by sibyl229** [comment]
Sure, I approved the PR. We are experiencing issues with CI on PR. So I need to talk with Olin or Manuel to merge PR, as they the CI issue blocks the PR from being merged.

**Comment by mluypaert** [comment]
> 
> 
> Sure, I approved the PR. We are experiencing issues with CI on PR. So I need to talk with Olin or Manuel to merge PR, as they the CI issue blocks the PR from being merged.

Not anymore ;)

**Comment by lpalbou** [comment]
Ok great, just as a confirmation: we are still merging on master today ? I wasn't in today call so I don't know if we have created a new branch for the release

**Pull request merged**
