### PR TITLE
adding help text for seq details.

### PR DESCRIPTION
**Pull request by scottcain**
I’m adding help text for the sequence details section but since I’ve been unable to get the website to run locally I’m committing untested code. I imagine that it is sufficiently simple that I’m likely to get it right, but somebody please really check for real :-)

### CODE REVIEW

**Comment by chris-grove** [comment]
@scottcain The stage branch has already (as in, yesterday or Monday) been pushed to test.alliancegenome.org, so any changes pushed to stage (as of now) will not be pushed out for 6.0.0. If we really want this in for 6.0.0, we need to discuss whether we can get it into the test branch for the release

**Comment by chris-grove** [comment]
@scottcain Sorry, since this is the UI repo, my statement may not be valid as we now have an independent build for UI changes

**Comment by scottcain** [comment]
Bad news and moderately good news: this PR is flawed and I have to figure out what's wrong. The moderately good news: I did get the website running locally on my ubuntu vm.

**Comment by scottcain** [comment]
Fixed a silly formatting issue. This can be merged if possible.

**Review by adamgibs — APPROVED** [review]

**Pull request merged**
