### PR TITLE
AGR-667 Update field for source link href

### PR DESCRIPTION
**Pull request by paaatrick**

### CODE REVIEW

**Comment by paaatrick** [comment]
It is required because it gets passed to the `href` attribute of the underlying `<a>` element.

**Comment by bryon-czoch** [comment]
Not always.  

```
warning.js?85a7:33 Warning: Failed prop type: The prop `href` is marked as required in `ExternalLink`, but its value is `undefined`.
    in ExternalLink (created by BasicDiseaseInfo)
    in BasicDiseaseInfo (created by DiseasePage)
    in div (created by Subsection)
    in Subsection (created by DiseasePage)
    in div (created by DiseasePage)
    in DiseasePage (created by Connect(DiseasePage))
    in Connect(DiseasePage) (created by RouterContext)
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by RouterContext)
    in RouterContext (created by Router)
    in ScrollBehaviorContext (created by Router)
    in Router (created by ReactApp)
    in Provider (created by ReactApp)
    in ReactApp
```

**Comment by paaatrick** [comment]
Okay. We can look at that later. But that doesn't really have anything to do with this change.

**Comment by bryon-czoch** [comment]
```
W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release: The following signatures were invalid: KEYEXPIRED 1507497109
W: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release' is not signed.
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)

```

**Comment by paaatrick** [comment]
Those are just warnings that show up in every travis build. They're not within our control. The log didn't really seem to contain the actual reason the build was marked as a failure. I reran it and it was fine.

**Pull request merged**
