### PR TITLE
Agr 672 - Fix the Main menu style

### PR DESCRIPTION
**Pull request by LucyHut**
Restored and enhanced the main navigation style - I'm making this pull request for develop as advised in Jira.

### CODE REVIEW

**Comment by paaatrick** [comment]
A few comments:

1) I feel like we're starting to accumulate too many shades of blue. Can you reuse one of the blues that we're already using (e.g. from the email/social bar) instead of introducing a new color for the hover highlight and submenu divider (#60BFDB)?
2) Can the first submenu item not have the border-top (see image)? It makes it look like the main item is bleeding into the sub item.
image

3) The submenu items have a lot of vertical padding, but the main items don't. Consider making them the same?
4) The subsection header lines (i.e. on the gene and disease pages) feel a little too strong with these changes. Maybe that line color (it's defined in `src/components/style.css` can be the same as the navbar lines (#ddd)?

**Comment by paaatrick** [comment]
Oh, also, it looks like this is a branch off of `release-1.0`, but the PR is requesting to merge into `develop`. You might need to close this PR and open a new one to go into `release-1.0`.

**Comment by ragingsquirrel3** [comment]
Personally, I kind of like the menu without the borders like it is currently, but I guess I have minimalistic aesthetic values.

**Comment by LucyHut** [comment]
@paaatrick, Ok thanks ... the  #60BFDB is the current background color of the  "More information"  link on the main page. I eyedropped the mouse hover event to get that color.  I tried the email/social bar background and thought it was too much. 

screen shot 2017-10-13 at 2 33 03 pm

**Comment by LucyHut** [comment]
@ragingsquirrel3 , I hear you but the current nav of the public site has borders  -- it kind of looks like everything is lumped together without borders .

screen shot 2017-10-13 at 2 23 57 pm

**Pull request closed without merging**
