### PR TITLE
Apollo docker integration

### PR DESCRIPTION
**Pull request by nathandunn**

### CODE REVIEW

**Comment by nathandunn** [comment]
This is needed because the variant service libraries don't like the space in the genome name, though they both point to the same place.

**Comment by paaatrick** [comment]
Some eslint errors to resolve. I think a couple of them might be fixed if you merge master into this branch but there's also one about the `console` statement you're introducing.

**Comment by paaatrick** [comment]
Also is it worth tying this into the `SPECIES` constant in `src/constants.js` instead of a one-off thing in the component?

**Comment by nathandunn** [comment]
@paaatrick  thanks.  I thought I'd forked off of master, but must have been an older one.  

I'll relint and retest here in one second.

**Comment by nathandunn** [comment]
@paaatrick  you had approved this, right?

**Comment by paaatrick** [comment]
Shoot first ask questions later right? 🙃 

Anyway, yeah I think we landed in the right place here.

**Pull request merged**
