### PR TITLE
Jscodeshift

### PR DESCRIPTION
**Pull request by bryon-czoch**

### CODE REVIEW

**Comment by nathandunn** [comment]
Looks good.

**Comment by bryon-czoch** [comment]
Dont forget to delete the branch.  Please note the proptypes change.

**Comment by nathandunn** [comment]
@bryon-czoch  Yeah, I saw that you used the general one instead of the facebook one.  I tested it briefly and didn't notice anything breaking.

**Comment by bryon-czoch** [comment]
importing prop-types like
`import React, {Component, PropTypes} from 'react';`
is deprecated

**Pull request merged**
