### PR TITLE
SCRUM-952 allow max-width of containers again, but keep margins, so a…

### PR DESCRIPTION
**Pull request by azurebrd**
…dd an extra container in Main to center the content container.  Fix About content punctuation.

### CODE REVIEW

**Review by valearna — APPROVED** [review]
Looks good @azurebrd. I haven't followed the whole story and I don't know if we have decided to have max-width to 100% or not, but I really like the latest iteration with the same amount of lateral whitespace as the other alliance pages

**Review by nuin — APPROVED** [review]

**Comment by azurebrd** [comment]
Thanks @valearna and @nuin  I've been messaging with Ceri during the meeting, and she changed the specs as we were tweaking it, but didn't change the ticket.

**Comment by azurebrd** [comment]
live

**Comment by nuin** [comment]
Is it OK to delete the branch?

**Comment by azurebrd** [comment]
My bad, yeah @nuin

**Comment by nuin** [comment]
No worries, we have so many branches ... Thanks @azurebrd

**Pull request merged**
