### PR TITLE
AGR-1522 IE11 fixes

### PR DESCRIPTION
**Pull request by paaatrick**
@sibyl229 apologies for undoing some of your recent work with this PR! I couldn't seem to get ES6 builtin functions (like `Object.assign`) working with the `babel-preset-react-app` preset. I kept getting errors about duplicate babel polyfill libraries being loaded. If you have other suggestions, please let me know or add commits to this branch.

### CODE REVIEW

**Comment by sibyl229** [comment]
Hi @paaatrick sorry about that. Roll back is a good plan! 

I'm a little concerned about the changes in src/index.js. With the change it will always load polyfill regardless whether a browser need it or not. This penalizes modern browsers by slowing them down to load things the don't need.

Maybe the src/index.js just need something like this:

```
  require(['@babel/polyfill', 'custom-event-polyfill'], () => {
    main();
  });
```

But if this doesn't work. Feel free to merge your fix in. And we can sort out the rest next release.

**Comment by paaatrick** [comment]
Yeah I initially tried to keep that in, but I still had no luck getting those ES6 builtins working on IE11. It wasn't immediately clear to me why, but I think it might have something to do with the fact that these newer versions of webpack and it's plugins and presets are becoming much more geared towards ES6 modules (`import`) as opposed to CommonJS (`require`). 

We should definitely take a closer look at this in 2.2. I'll open a new ticket for that. I think the right way to do it now is outlined here: https://itnext.io/lazy-loading-polyfills-4b85c4951e73

**Comment by paaatrick** [comment]
Created case AGR-1529

**Comment by sibyl229** [comment]
Thanks @paaatrick 👍 Let's revisit for 2.2

**Pull request merged**
