### PR TITLE
footer initial template and data for WormBase

### PR DESCRIPTION
**Pull request by ianlongden**
Adding early as it is my first venture into react etc. WormBase done so just need to add other members, but you can look at this and decide on any style changes etc that may be wanted. Just giving people advance warning.

### CODE REVIEW

**Review by azurebrd — DISMISSED** [review]
Generalizing the labels to links makes sense.  I think @nuin did the resources as hardcoded html to leave it open for a wordPress import in the future, so I'll let him comment on that.

**Review by azurebrd — COMMENTED** [review]
@ianlongden Actually, I'm wondering whether it'd be better if footer_obj was an array of objects, then the order would be explicit, but also we could add other parameters in the future, like font color, whether they open in the same tab or another tab, if some should be bigger font for some reason, and other stuff like that.

**Comment by ianlongden** [comment]
> @ianlongden Actually, I'm wondering whether it'd be better if footer_obj was an array of objects, then the order would be explicit, but also we could add other parameters in the future, like font color, whether they open in the same tab or another tab, if some should be bigger font for some reason, and other stuff like that.


yep. Good call an array would keep the order. I will change that.

**Comment by nuin** [comment]
I would change the CSS before merging, the font colours really don't stand out

image


but it's your call @azurebrd

**Comment by azurebrd** [comment]
@ianlongden I agree with @nuin , I hadn't looked at what it actually looked like.  I imagine we'd want to share the same background color + font color styling that comes from titleBar__<mod>.  It'll probably need a tweak to apply to the <a> elements.  

Separately, at some point we might end up splitting up .titleBar__<mod> into something like backgroundColor__<mod> and fontColor__<mod>  because I was tweaking adding a box-shadow to the about button, but didn't want to apply it to the title bar by using the same .titleBar__<mod> for the button styling.  This might end up mattering more as we use the same colours for other elements.

**Comment by azurebrd** [comment]
@nuin Do you have an opinion about my suggestion of it being an array of objects instead of key-value pairs ?   I see that @ianlongden has made it an array of arrays, which works, but it forces tracking of index, instead of key.  I thought the content.js could be something like
```footer: [
      { 'label': 'Nomenclature', 
        'link': 'https://wormbase.org/about/userguide/nomenclature#gi9m5c264k8be0afldh71j3--10'},
      {'label': 'Tools', 
        'link':  'https://wormbase.org/tools#0--10'],
    ...]```
In case we later need to add 'target' or 'fontColor' or something else.
This totally works as-is though.

**Review by azurebrd — DISMISSED** [review]

**Comment by nuin** [comment]
@azurebrd I think right now both approaches are valid, but I agree with your point and suggestion, it gives more flexibility for future changes.

**Comment by azurebrd** [comment]
Thanks @nuin

**Comment by azurebrd** [comment]
@ianlongden If you wanted to try to update the styling for the links, I'd probably do something like in the resources, where there's a div with style resourceDiv  and the style.scss has an entry `.resourceDiv p`  which applies the styling to only the <p> elements that are within the (only-one) elements with a resourceDiv class.  So you'd probably add a  footerDiv style to a div in the footer container, then make a `.footerDiv a` in the style.scss that gives it the colour properties you'd want.  Since you'd potentially want different font colours for the different mods, you'd probably make it a footerDiv__<mod> instead of just footerDiv, and then have separate sections for each mod with a <space>a in the style.scss  (I might have made this sound more complicated than it is, I'm sure there's other ways of doing this)

**Comment by nuin** [comment]
@ianlongden @azurebrd There is also some refactoring that can be done on `style.css` as new classes for the footer can be added to avoid collision between title bar and footer. And these classes can be together in the CSS

**Review by azurebrd — APPROVED** [review]
Thanks for taking this on @ianlongden and going along with so much backseat coding.  It's your last day, so let's get this merged and out of your mind.  I agree with @nuin about refactoring the style.scss although I'm not sure what's best, so I hope Paulo can take that on after this is merged.

**Comment by azurebrd** [comment]
live

**Comment by azurebrd** [comment]
@nuin If you take on the style refactor, could you also add something to make the <a> text color match the expected font color ?  If not, I can do it when you're done

**Comment by nuin** [comment]
@azurebrd I will take a look, we need to override the global `a` style, I will take a look

**Comment by azurebrd** [comment]
@nuin Ah, gotcha, I didn't realize that.  Thanks.

**Comment by ianlongden** [comment]
I am happyish with what is there now. Need to change text color and add actual icons for twitter/standford etc but it should be okay as a MVP. Please feel free to change what ever you want while I am away,.

**Pull request merged**
