### PR TITLE
AGR-2537 add json path to associated gene attribute

### PR DESCRIPTION
**Pull request by cmpich**

### CODE REVIEW

**Comment by sibyl229** [comment]
@cmpich great! Thanks for doing this. What is the filter for this? It can be passed in as `filterName: 'xxx',` (without the `filter.` part). If you paste it here, I can add it into the code.

**Comment by cmpich** [comment]
The filter name is:
filter.associatedGeneSymbol

**Comment by sibyl229** [comment]
@cmpich great, I pushed the change. Build is down right now. I will run the code locally when it's up before merging.

**Review by sibyl229 — APPROVED** [review]
@cmpich you changes looks good to me. I change the Sequence Feature Associated Gene to a link. Feel free to merge when you get a chance to look it over.

**Comment by sibyl229** [comment]
@cmpich actually will merge this right now. You might want to create a new feature branch from `master` branch, because this branch is missing a critical fix available there. 

Also please use the naming convention AGR-NNN-branchname for jira integration.

**Pull request merged**
