### PR TITLE
Fix 648 jbrowse buffer

### PR DESCRIPTION
**Pull request by nathandunn**
Fixes AGR-648 and AGR-656

### CODE REVIEW

**Comment by paaatrick** [comment]
AGR-648 is marked with fix version 1.0, but this requesting to merge into develop. Is that correct?

**Comment by nathandunn** [comment]
Good call.  If this looks good go ahead and merge and I’ll create another pr.

Nathan

**Comment by paaatrick** [comment]
I'd suggest just opening another PR and closing this one. I sweep changes from release-1.0 back into develop periodically.

**Comment by nathandunn** [comment]
Okay.  I didn’t know that.    K.  I will do that.

**Comment by nathandunn** [comment]
replacing in favor of #97

**Pull request closed without merging**
