### PR TITLE
AGR-1651

### PR DESCRIPTION
**Pull request by felixgondwe**
- add ellipsis in front of automated gene symbol text field

### CODE REVIEW

**Comment by gildossantos** [comment]
Olin says on the Slack #technical-calls channel that "Release branches have been taken please make any changes into release-3.2.0".Should this PR get merged into "release 3.2.0" branch

**Comment by paaatrick** [comment]
Yes, definitely. I've changed the merge base to `release-3.2.0`. I was going to leave it up to @kevinschaper to review and merge since I assume he's more familiar with the issue.

**Comment by kevinschaper** [comment]
We probably should bump this to draft and I'll end up taking it on. There are more fields to support, but also we don't want to show an ellipse if it's actually matching against the first sentence.

**Comment by gildossantos** [comment]
The ticket's specs should've been clearer.
If it's the first sentence, it should have only a trailing ellipsis.
If it's the last sentence, it should have only a leading ellipsis.
If it's a middle sentence, it should have ellipses on either side.

**Pull request closed without merging**
