### PR TITLE
AGR-2124 fix for allele exclusion bug

### PR DESCRIPTION
**Pull request by adamgibs**
Added category to the list of params to be ignored for possible exclusion.

### CODE REVIEW

**Comment by sibyl229** [comment]
@adamgibs do you need someone in particular to look at this? or just waiting for anyone to approve and pull it in?

**Comment by adamgibs** [comment]
@sibyl229 Just waiting for anyone to approve it. Should I have requested a reviewer?

**Review by sibyl229 — APPROVED** [review]

**Comment by sibyl229** [comment]
@adamgibs I went ahead and added myself as a reviewer. In the future, adding reviewer(s) would be nice. So people know whether it's intended for them. 
There is some discussion on #devOp about an issue with the CI.

**Comment by adamgibs** [comment]
@sibyl229 Got it. Thanks!

**Pull request merged**
