### PR TITLE
AGR-1863 add rendering for the phenotypes column

### PR DESCRIPTION
**Pull request by sibyl229**
I assumed the column filter is called `filter.phenotypes`.

### CODE REVIEW

**Comment by FB-ping** [comment]
you forget to change this line: // dataField: 'phenotypes', src/components/interaction/GeneGeneticInteractionDetailTable.js
should also you add a download link same as molecular interaction ?

**Comment by sibyl229** [comment]
@FB-ping good catch! Fixed.

**Comment by FB-ping** [comment]
test fine on local server

**Review by FB-ping — APPROVED** [review]
test fine on local server

**Pull request merged**
