### PR TITLE
scrum-618 fix key warning

### PR DESCRIPTION
**Pull request by FB-ping**
add key for News component to fix the warning

### CODE REVIEW

**Review by azurebrd — COMMENTED** [review]
That's a weird key value, it's the URL, right ?  Using a count didn't work ?

**Comment by FB-ping** [comment]
yes, it is the url of that news, as long as unique.  counter value may also be good.

**Comment by azurebrd** [comment]
@FB-ping Did you try what I suggested on the other pull request ?  Github code doesn't handle backticks well, I'll tag you on the comment I mentioned it in #scrum-blueteam.   I think doing it with a key that refers to the type of element, and the count will communicate more about what the div is for.
`<div key={``post ${count}``} className={style.postContainer}>`

**Comment by FB-ping** [comment]
will try tonight.

**Pull request closed without merging**
