### PR TITLE
Agr 743 -Use Wordpress page slug in all react routes mapping to Wordpress pages

### PR DESCRIPTION
**Pull request by LucyHut**
All the routes to Wordpress pages are now using the page slug - 
Also as per last meeting - November 1st - I worked on the menu items to make it look less
crowded :)

### CODE REVIEW

**Comment by LucyHut** [comment]
@oblodgett , yes - the list we keep in constants.js only contains pages that are part of building the menu and sub-menus

**Comment by bryon-czoch** [comment]
ERROR in ./src/routes.js

/Users/bczoch/flybase/agr_ui/src/routes.js
   2:32  error  'IndexRoute' is defined but never used  no-unused-vars
  12:10  error  'WP_PAGES' is defined but never used    no-unused-vars

✖ 2 problems (2 errors, 0 warnings)


ERROR in ./src/containers/wordpress/index.js

/Users/bczoch/flybase/agr_ui/src/containers/wordpress/index.js
  37:44  error  Missing semicolon  semi

✖ 1 problem (1 error, 0 warnings)

**Comment by LucyHut** [comment]
Will take a look Tanks

**Comment by bryon-czoch** [comment]
I've fixed all but one error/warning.  Make sure you pull in my edits before working on it

**Comment by LucyHut** [comment]
@bryon-czoch , I just did - it all looks good. 
@oblodgett , I updated the urls in bin/build_sitemap.js to use page slugs

**Comment by bryon-czoch** [comment]
One warning left...

```Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `TableBody`. See https://fb.me/react-warning-keys for more information.```

Do you see what's causing it?

**Comment by LucyHut** [comment]
@bryon-czoch ,I don't see this on my side

**Comment by bryon-czoch** [comment]
Right click-> click 'Inspect' in your browser to pull up the console.

**Comment by LucyHut** [comment]
@bryon-czoch , I coud not see the warning --  Is this specific to this branch?  I'm asking because the component throwing the warning is not part of Wordpress components and was not touched in this branch.

**Comment by oblodgett** [comment]
@LucyHut now that you mention it I need to get a quick fix in to the sitemap, will commit shortly.

**Comment by bryon-czoch** [comment]
@LucyHut you didn't list me as a reviewer...

**Comment by oblodgett** [comment]
@bryon-czoch just added you as a reviewer.

**Comment by LucyHut** [comment]
@bryon-czoch , sorry it was not intentional : ) Thank you @oblodgett

**Pull request merged**
