### PR TITLE
Scrum 618 news

### PR DESCRIPTION
**Pull request by FB-ping**
news section for scrum-618

### CODE REVIEW

**Review by valearna — DISMISSED** [review]

**Review by FB-ping — COMMENTED** [review]
merge some css change

**Review by azurebrd — APPROVED** [review]
Cool about :global(.shareaddy) { display: none; }  and seeing how parseWordpressPosts switches the type of mapping

**Comment by azurebrd** [comment]
pulled to live

**Comment by nuin** [comment]
There's an issue/warning with the news

```
[Error] Warning: Each child in a list should have a unique "key" prop.

Check the render method of `WordpressNews`. See https://reactjs.org/link/warning-keys for more information.
div
WordpressNews@http://localhost:2992/main.js:42318:17
div
div
News@http://localhost:2992/main.js:41865:29
div
div
MODLanding@http://localhost:2992/main.js:41721:56
Route@http://localhost:2992/vendor.js:95802:34
Switch@http://localhost:2992/vendor.js:96008:34
div
div
div
div
Layout@http://localhost:2992/main.js:40542:10
Connect(Layout)@http://localhost:2992/vendor.js:92987:75
withRouter(Connect(Layout))@http://localhost:2992/vendor.js:96063:36
RouteListener@
withRouter(RouteListener)@http://localhost:2992/vendor.js:96063:36
ScrollContext@http://localhost:2992/vendor.js:95159:19
withRouter(ScrollContext)@http://localhost:2992/vendor.js:96063:36
Router@http://localhost:2992/vendor.js:95431:34
BrowserRouter@http://localhost:2992/vendor.js:94386:40
ReleaseContextProvider@http://localhost:2992/main.js:46066:21
ReactQueryConfigProvider@http://localhost:2992/vendor.js:92063:20
Provider@http://localhost:2992/vendor.js:92700:19
ReactApp@
	printWarning (vendor.js:104208)
	error (vendor.js:104184)
	validateExplicitKey (vendor.js:105077)
	validateChildKeys (vendor.js:105104)
	jsxWithValidation (vendor.js:105265)
	WordpressNews (main.js:42332:101)
	renderWithHooks (vendor.js:74993)
	updateFunctionComponent (vendor.js:77364)
	beginWork$1 (vendor.js:83943)
	performUnitOfWork (vendor.js:82782)
	workLoopSync (vendor.js:82710)
	renderRootSync (vendor.js:82673)
	performSyncWorkOnRoot (vendor.js:82296)
	performSyncWorkOnRoot
	(anonymous function) (vendor.js:71335)
	unstable_runWithPriority (vendor.js:120826)
	flushSyncCallbackQueueImpl (vendor.js:71330)
	flushSyncCallbackQueue (vendor.js:71317)
	batchedUpdates$1 (vendor.js:82390)
	(anonymous function) (vendor.js:90127)
	promiseReactionJob```

**Comment by azurebrd** [comment]
Not sure where the error is, I think I usually delete stuff until the error goes away, then bring it all back and add a key prop based on a common identifier and some varying variable.  Say the issue was on line 39
<div className={style.postContainer}>
Then make it 
<div key={`post ${count}`} className={style.postContainer}>

**Comment by FB-ping** [comment]
This kind of errors happened when we put create lists of elements, most
likely when we fetch wordpress, we just need to add 1 id parameter with
some unique string. will look at on Monday.

**Comment by azurebrd** [comment]
@FB-ping Yeah, I'm assuming it's on the div on line 39.  I put in a way to add a key the way react would want, but didn't realize github wasn't showing the code.  I tried to format it to show, but it does it with backticks, so it hides the backticks in the sample code.  I've got it to show doublebackticks, but react should only need single backticks where there's 2.

**Pull request merged**
