### PR TITLE
SCRUM-976, SCRUM-977

### PR DESCRIPTION
**Pull request by gildossantos**
More catches of incorrect MOD references. Changes to FlyBase and WormBase URLs and MGD title, per suggestions from @azurebrd. Thanks! Hopefully that's the last of them.

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
Thanks @gildossantos !

**Comment by azurebrd** [comment]
@gildossantos Ah, but there's an issue with the bannerstyle of a test

**Comment by azurebrd** [comment]
@gildossantos I'm on a call about WB stuff, but my guess is that the tests get values from the content.js keying off of 'wb' and now that's changed to 'wormbase'

**Comment by gildossantos** [comment]
Thanks @azurebrd. Just submitted change to the test file  - let's see if changing `wb` to `wormbase` fixes it.

**Review by azurebrd — APPROVED** [review]

**Comment by azurebrd** [comment]
live, looks good !

**Pull request merged**
